version: 2

sources:
  - name: zengrc
    database: '{{ env_var("SNOWFLAKE_LOAD_DATABASE") }}'
    schema: tap_zengrc
    loaded_at_field: __loaded_at
    loader: tap_zengrc
    description: '{{ doc("zengrc_desc") }}'

    quoting:
      database: true
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}

    tables:
      - name: assessments
        description: '{{ doc("zengrc_assessments_desc") }}'
      - name: audits
        description: '{{ doc("zengrc_audits_desc") }}'
      - name: controls
        description: '{{ doc("zengrc_controls_desc") }}'
      - name: objectives
        description: '{{ doc("zengrc_objectives_desc") }}'