version: 2
models:
- name: driveload_clari_export_forecast_net_iacv_source
  description: Clari export forcast data primariliy for use by the finance team.
  columns:
    - name: user
      tests:
      - not_null
